[tool.poetry]
name = "audio-offset-finder"
version = "0.1.0"
description = ""
authors = ["Andrew Chen <hello@andrewtheguy.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
apscheduler = "^3.10.4"
python = "^3.12"
numpy = "^1.26.4"
matplotlib = "^3.9.0"
ffmpeg-python = "^0.2.0"
pyloudnorm = "^0.1.1"
requests = "^2.32.2"
pytz = "2024.2"
jinja2 = "^3.1.3"
python-dotenv = "^1.0.1"
andrew_utils= { git = "https://github.com/andrewtheguy/andrew_utils.git", branch = "main" }
setuptools = "^69.5.1"
boto3 = "^1.34.103"
pypinyin = "^0.51.0"
scikit-learn = "^1.5.0"
soundfile = "^0.12.1"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.1"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
