[tool.poetry]
name = "audio-offset-finder"
version = "0.1.0"
description = ""
authors = ["Andrew Chen <andrew@jaanuu.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
apscheduler = "^3.10.4"
python = "^3.12"
librosa = "*"
numpy = "*"
matplotlib = "*"
ffmpeg-python = "*"
pyloudnorm = "*"
requests = "*"
webdav4 = "*"
paramiko = "*"
pytz = "*"
jinja2 = "^3.1.3"
python-dotenv = "^1.0.1"
andrew_utils= { git = "https://github.com/andrewtheguy/andrew_utils.git", branch = "main" }
setuptools = "^69.5.1"
feedparser = "^6.0.11"
boto3 = "^1.34.103"
dtaidistance = "^2.3.11"

[tool.poetry.group.test.dependencies]
pytest = "^8.2.1"
flake8 = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
