[tool.poetry]
name = "audio-offset-finder"
version = "0.1.0"
description = ""
authors = ["Andrew Chen <andrew@jaanuu.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
librosa = "*"
numpy = "*"
matplotlib = "*"
ffmpeg-python = "*"
pydub = "*"
pyloudnorm = "*"
requests = "*"
#webdav4 = "*"
paramiko = "*"
pytz = "*"
jinja2 = "^3.1.3"
python-dotenv = "^1.0.1"
upload_utils= { git = "https://github.com/andrewtheguy/upload_utils.git", branch = "main" }
andrew_utils= { git = "https://github.com/andrewtheguy/andrew_utils.git", branch = "main" }
setuptools = "^69.5.1"
dtw-python = "^1.4.2"
pymongo = {extras = ["srv"], version = "^4.7.1"}
feedparser = "^6.0.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
